import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(
        description="Plot time-domain Ez signals recorded by FDTD probes."
    )
    parser.add_argument(
        "--input",
        default="fdtd_probes_results.csv",
        help="Input CSV file generated by the C++ FDTD solver."
    )
    parser.add_argument(
        "--output",
        default="results/time_domain_signals.png",
        help="Output figure path."
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_path}\n"
            "Please run the C++ FDTD solver first to generate fdtd_probes_results.csv."
        )

    data = np.loadtxt(input_path, delimiter=",", skiprows=1)

    time_step = data[:, 0]
    probe1_ez = data[:, 1]
    probe2_ez = data[:, 2]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 5))
    plt.plot(time_step, probe1_ez, label="Probe 1 Ez")
    plt.plot(time_step, probe2_ez, label="Probe 2 Ez")

    plt.xlabel("Time step")
    plt.ylabel("Ez amplitude")
    plt.title("Time-domain FDTD Probe Signals")
    plt.legend()
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    print(f"Saved figure to: {output_path}")


if __name__ == "__main__":
    main()
